### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by jetXS** [hackappcom/iloot#23]
I got 2 iClouds account, this error is happening with one of them.

When trying to download files:

Traceback (most recent call last):
  File "C:\Users\XXXX\Desktop\iloot-master\iloot.py", line 610, in <mod
ule>
    download_backup(args.apple_id, args.password, args.output, args.item_types,
args.snapshot, args.combined, args.itunes_style, args.domain)
  File "C:\Users\ XXXX\Desktop\iloot-master\iloot.py", line 572, in down
load_backup
    client.download(UDID, types)
  File "C:\Users\ XXXX\Desktop\iloot-master\iloot.py", line 450, in down
load
    self.authorize_get(authTokens, snapshot)
  File "C:\Users\ XXXX\Desktop\iloot-master\iloot.py", line 247, in auth
orize_get
    data = self.download_chunks(container)
  File "C:\Users\ XXXX\Desktop\iloot-master\iloot.py", line 286, in down
load_chunks
    container.host_info.uri, "", headers)
  File "C:\Users\ XXXX\Desktop\iloot-master\iloot.py", line 91, in probo
buf_request
    request = conn.request(method, url, body, headers)
  File "C:\Python27\lib\httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "C:\Python27\lib\httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "C:\Python27\lib\httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "C:\Python27\lib\httplib.py", line 850, in _send_output
    self.send(msg)
  File "C:\Python27\lib\httplib.py", line 812, in send
    self.connect()
  File "C:\Python27\lib\httplib.py", line 1216, in connect
    server_hostname=server_hostname)
  File "C:\Python27\lib\ssl.py", line 350, in wrap_socket
    _context=self)
  File "C:\Python27\lib\ssl.py", line 566, in __init__
    self.do_handshake()
  File "C:\Python27\lib\ssl.py", line 788, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c
:581)

**Comment by jetXS** [comment]
After a day of trying kinda everything : 

-I had the same error occurring on a fresh VMWare installation of Windows 7 and a python installation+libraries.

-I had the same error occurring installing using MacPort python installation+libraries.

-I had the same error occurring on a fresh BootCamp installation of Windows 8.1 and python installation+libraries.

It somehow succeeded (why, I don't know... ) by uninstalling MacPort/python/librarires and reinstalling only python 2.9 (with pip included) on OS X Yosemite... Would it be OS X related ? I know that there is a lot of problems since mavericks on OS X with SSL and SMTP... My knowledge can't confirm that this is related...

**Comment by imton** [comment]
iloot.py
````python
...
from pbuf import decode_protobuf_array, encode_protobuf_array
from util import hexdump

add this >>>>> import requests.packages.urllib3 as urllib3
add this  >>>>> urllib3.disable_warnings()
...
````
