### ISSUE TITLE
SSL Certificate Verify Failed 

### ISSUE THREAD

**Issue by bertjames32** [hackappcom/iloot#34]
Trying to download the full backup in itunes format. Also have got it when trying to do the normal download with correct file names.   and get the following after about 10 minutes:

Traceback (most recent call last):
  File "iloot.py", line 611, in <module>
    download_backup(args.apple_id, args.password, args.output, args.item_types,
args.snapshot, args.combined, args.itunes_style, args.domain)
  File "iloot.py", line 573, in download_backup
    client.download(UDID, types)
  File "iloot.py", line 451, in download
    self.authorize_get(authTokens, snapshot)
  File "iloot.py", line 247, in authorize_get
    data = self.download_chunks(container)
  File "iloot.py", line 287, in download_chunks
    container.host_info.uri, "", headers)
  File "iloot.py", line 91, in probobuf_request
    request = conn.request(method, url, body, headers)
  File "C:\Python27\lib\httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "C:\Python27\lib\httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "C:\Python27\lib\httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "C:\Python27\lib\httplib.py", line 850, in _send_output
    self.send(msg)
  File "C:\Python27\lib\httplib.py", line 812, in send
    self.connect()
  File "C:\Python27\lib\httplib.py", line 1216, in connect
    server_hostname=server_hostname)
  File "C:\Python27\lib\ssl.py", line 350, in wrap_socket
    _context=self)
  File "C:\Python27\lib\ssl.py", line 566, in __init__
    self.do_handshake()
  File "C:\Python27\lib\ssl.py", line 788, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c
:581)

**Comment by GarethWright** [comment]
yup get that too. Win7
