### ISSUE TITLE
memory error

### ISSUE THREAD

**Issue by ediaz369** [hackappcom/iloot#36]
Runs for awhile and then I get a memory error.

Traceback (most recent call last):
  File "/root/Desktop/iloot-master/iloot.py", line 611, in <module>
    download_backup(args.apple_id, args.password, args.output, args.item_types, args.snapshot, args.combined, args.itunes_style, args.domain)
  File "/root/Desktop/iloot-master/iloot.py", line 573, in download_backup
    client.download(UDID, types)
  File "/root/Desktop/iloot-master/iloot.py", line 451, in download
    self.authorize_get(authTokens, snapshot)
  File "/root/Desktop/iloot-master/iloot.py", line 247, in authorize_get
    data = self.download_chunks(container)
  File "/root/Desktop/iloot-master/iloot.py", line 287, in download_chunks
    container.host_info.uri, "", headers)
  File "/root/Desktop/iloot-master/iloot.py", line 100, in probobuf_request
    data = response.read()
  File "/usr/lib/python2.7/httplib.py", line 548, in read
    s = self._safe_read(self.length)
  File "/usr/lib/python2.7/httplib.py", line 652, in _safe_read
    return ''.join(s)

**Comment by xlbillyboylx** [comment]
Yeah I get the same thing sometimes.
