### ISSUE TITLE
Script fails with... 

### ISSUE THREAD

**Issue by dwkns** [hackappcom/iloot#45]
The script is not working for me on 10.10.3 (14D136) and Python 2.7.9

	$python iloot.py d******@******.com P********d
	
Gives :

	Working with d******@******.com : P********d
	Output directory : output
	Traceback (most recent call last):
	  File "iloot.py", line 627, in <module>
	    download_backup(args.apple_id, args.password, args.output, args.item_types, args.snapshot, args.combined, args.itunes_style, args.domain, args.threads)
	  File "iloot.py", line 547, in download_backup
	    authenticateResponse = plist_request("setup.icloud.com", "POST", "/setup/authenticate/$APPLE_ID$", "", {"Authorization": auth})
	  File "iloot.py", line 73, in plist_request
	    request = conn.request(method, url, body, headers)
	  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in request
	    self._send_request(method, url, body, headers)
	  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1035, in _send_request
	    self.endheaders(body)
	  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 997, in endheaders
	    self._send_output(message_body)
	  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 850, in _send_output
	    self.send(msg)
	  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 812, in send
	    self.connect()
	  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1212, in connect
	    server_hostname=server_hostname)
	  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 350, in wrap_socket
	    _context=self)
	TypeError: __init__() got an unexpected keyword argument 'server_hostname'
	

Any ideas?

**Comment by Marfusios** [comment]
Same as #38

**Comment by dwkns** [comment]
Yep. It is. Closing...
