### ISSUE TITLE
SSLError: [Errno 8] _ssl.c:510: EOF occurred in violation of protocol

### ISSUE THREAD

**Issue by herrgutt** [hackappcom/iloot#47]
Been getting this error in the middle of a download (about 10% downloaded). Sometimes if you restart it will download something it has not downloaded before then stop again. 8 gb ram and python version 2.7. This will cause the backup to stall about 10% in.. Any solutions to this will be greatly appreciated.

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\gevent\greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "C:\Python27\iloot\iloot.py", line 303, in download_chunks
    container.host_info.uri, "", headers)
  File "C:\Python27\iloot\iloot.py", line 93, in probobuf_request
    request = conn.request(method, url, body, headers)
  File "C:\Python27\lib\httplib.py", line 995, in request
    self._send_request(method, url, body, headers)
  File "C:\Python27\lib\httplib.py", line 1029, in _send_request
    self.endheaders(body)
  File "C:\Python27\lib\httplib.py", line 991, in endheaders
    self._send_output(message_body)
  File "C:\Python27\lib\httplib.py", line 844, in _send_output
    self.send(msg)
  File "C:\Python27\lib\httplib.py", line 806, in send
    self.connect()
  File "C:\Python27\lib\httplib.py", line 1198, in connect
    self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file)
  File "C:\Python27\lib\site-packages\gevent\ssl.py", line 383, in wrap_socket
    ciphers=ciphers)
  File "C:\Python27\lib\site-packages\gevent\ssl.py", line 94, in __init__
    self.do_handshake()
  File "C:\Python27\lib\site-packages\gevent\ssl.py", line 305, in do_handshake
    return self._sslobj.do_handshake()
SSLError: [Errno 8] _ssl.c:510: EOF occurred in violation of protocol
<Greenlet at 0xbb8f048L: <bound method MobileBackupClient.download_chunks of <__
main__.MobileBackupClient object at 0x00000000031784A8>>([<chunkserver_pb2.FileC
hecksumStorageHostChunkList)> failed with SSLError

Traceback (most recent call last):
  File "C:\Python27\iloot\iloot.py", line 629, in <module>
    download_backup(args.apple_id, args.password, args.output, args.item_types,
args.snapshot, args.combined, args.itunes_style, args.domain, args.threads)
  File "C:\Python27\iloot\iloot.py", line 590, in download_backup
    client.download(UDID, types)
  File "C:\Python27\iloot\iloot.py", line 467, in download
    self.authorize_get(authTokens, snapshot)
  File "C:\Python27\iloot\iloot.py", line 255, in authorize_get
    for res in pool.imap_unordered(self.download_chunks, containers):
  File "C:\Python27\lib\site-packages\gevent\pool.py", line 222, in next
    raise value.exc
ssl.SSLError: [Errno 8] _ssl.c:510: EOF occurred in violation of protocol

**Comment by abyssgazer257** [comment]
Modify the original script to not download files that already exist. It's the only solution.

**Comment by herrgutt** [comment]
Thanks for the soulution!

(I need help with modifying the original script to not download files that already exists)

I have decreased to only one thread.. Yep it's really slow.(Is there a way to keep the number of threads a little higher without getting the SSL error?)  But I am still getting another error, please see below:

Traceback (most recent call last):
  File "C:\Python27\iloot\iloot.py", line 629, in <module>
    download_backup(args.apple_id, args.password, args.output, args.item_types,
args.snapshot, args.combined, args.itunes_style, args.domain, args.threads)
  File "C:\Python27\iloot\iloot.py", line 590, in download_backup
    client.download(UDID, types)
  File "C:\Python27\iloot\iloot.py", line 467, in download
    self.authorize_get(authTokens, snapshot)
  File "C:\Python27\iloot\iloot.py", line 275, in authorize_get
    self.write_file(file, decrypted_chunks, snapshot)
  File "C:\Python27\iloot\iloot.py", line 335, in write_file
    with open(path, "wb") as ff:
IOError: [Errno 2] No such file or directory: u'output\\5294e04dab61df8b2ae8d1ba
4bc9cdc36e30ce7d\\snapshot_1/AppDomain-com.cardinalblue.PicCollage\\Documents/co
llage_53e3add26b1dd671/resources/resource_assets_library_asset_asset_PNG_id_9625
88A5_4B23_45D0_B320_4FC83DA46402_ext_PNG_device__459a6f551e9b645fd5cab871e74ebae
1'

Any help will be rewarded with respect and a BIG thanks! :+1:

**Comment by abyssgazer257** [comment]
I can tell you how I did it, it was a dirty fix so it won't work if you do something like maintaining itunes filenames or using --combined.

In function download() I added:

            def file_doesnt_exist(a_file):
                directory = os.path.join(self.output_folder, re.sub(r'[:|*<>?"]', "_", "snapshot_"+str(snapshot)+"/"+a_file.Domain))
                path = os.path.join(directory, a_file.RelativePath)
                return not os.path.isfile(path)

Then lower down I added:

files = filter(file_doesnt_exist, files)


I know of no way to use more than one thread and not get SSL errors. Python isn't my cup of tea and from what I gather whoever made this script was pretty sloppy, but effective, so I can't complain.

**Comment by alytic** [comment]
Sorry to be a pain, but which lines did you add the codes at?

**Comment by herrgutt** [comment]
Hello and thanks a lot for the help this far.

Could you point out the lines where im about to add the code? I cant seem to get it to work. Thanks in advance.
