### ISSUE TITLE
Couldn't find index page for 'pytz' (maybe misspelled?)

### ISSUE THREAD

**Issue by fnatalucci** [hackappcom/iloot#53]
Requirement already satisfied (use --upgrade to upgrade): pycrypto in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Downloading/unpacking protobuf (from -r requirements.txt (line 4))
  Downloading protobuf-2.6.1.tar.gz (188kB): 188kB downloaded
  Running setup.py (path:/tmp/pip_build_root/protobuf/setup.py) egg_info for package protobuf
    Download error on https://pypi.python.org/simple/pytz/: [Errno 111] Connection refused -- Some packages may not be found!
    Couldn't find index page for 'pytz' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: [Errno 111] Connection refused -- Some packages may not be found!
    No local packages or download links found for pytz>=2010
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/protobuf/setup.py", line 200, in <module>
        "Protocol Buffers are Google's data interchange format.",
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 239, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 264, in fetch_build_eggs
        replace_conflicting=True
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 620, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 858, in best_match
        return self.obtain(req, installer) # try and download/install
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 870, in obtain
        return installer(requirement)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 314, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 610, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pytz>=2010')
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/pytz/: [Errno 111] Connection refused -- Some packages may not be found!

Couldn't find index page for 'pytz' (maybe misspelled?)

Download error on https://pypi.python.org/simple/: [Errno 111] Connection refused -- Some packages may not be found!

No local packages or download links found for pytz>=2010

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/protobuf/setup.py", line 200, in <module>

    "Protocol Buffers are Google's data interchange format.",

  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 239, in __init__

    self.fetch_build_eggs(attrs.pop('setup_requires'))

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 264, in fetch_build_eggs

    replace_conflicting=True

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 620, in resolve

    dist = best[req.key] = env.best_match(req, ws, installer)

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 858, in best_match

    return self.obtain(req, installer) # try and download/install

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 870, in obtain

    return installer(requirement)

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 314, in fetch_build_egg

    return cmd.easy_install(req)

  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 610, in easy_install

    raise DistutilsError(msg)

distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pytz>=2010')

**Comment by fnatalucci** [comment]
SOLVED: with pip install pytz
