### ISSUE TITLE
No local packages or download links found for python-dateutil>=1.4,<2

### ISSUE THREAD

**Issue by fnatalucci** [hackappcom/iloot#54]
# sudo pip install -r requirements.txt --proxy http://proxyCustom:8080

Requirement already satisfied (use --upgrade to upgrade): gevent in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Downloading/unpacking hurry.filesize (from -r requirements.txt (line 2))
  Downloading hurry.filesize-0.9.tar.gz
  Running setup.py (path:/tmp/pip_build_root/hurry.filesize/setup.py) egg_info for package hurry.filesize
    
Requirement already satisfied (use --upgrade to upgrade): pycrypto in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Downloading/unpacking protobuf (from -r requirements.txt (line 4))
  Downloading protobuf-2.6.1.tar.gz (188kB): 188kB downloaded
  Running setup.py (path:/tmp/pip_build_root/protobuf/setup.py) egg_info for package protobuf
    Download error on https://pypi.python.org/simple/python-dateutil/: [Errno 111] Connection refused -- Some packages may not be found!
    Download error on https://pypi.python.org/simple/: [Errno 111] Connection refused -- Some packages may not be found!
    No local packages or download links found for python-dateutil>=1.4,<2
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/protobuf/setup.py", line 200, in <module>
        "Protocol Buffers are Google's data interchange format.",
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 239, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 264, in fetch_build_eggs
        replace_conflicting=True
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 620, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 858, in best_match
        return self.obtain(req, installer) # try and download/install
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 870, in obtain
        return installer(requirement)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 314, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 610, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('python-dateutil>=1.4,<2')
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/python-dateutil/: [Errno 111] Connection refused -- Some packages may not be found!

Download error on https://pypi.python.org/simple/: [Errno 111] Connection refused -- Some packages may not be found!

No local packages or download links found for python-dateutil>=1.4,<2

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/protobuf/setup.py", line 200, in <module>

    "Protocol Buffers are Google's data interchange format.",

  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 239, in __init__

    self.fetch_build_eggs(attrs.pop('setup_requires'))

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 264, in fetch_build_eggs

    replace_conflicting=True

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 620, in resolve

    dist = best[req.key] = env.best_match(req, ws, installer)

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 858, in best_match

    return self.obtain(req, installer) # try and download/install

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 870, in obtain

    return installer(requirement)

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 314, in fetch_build_egg

    return cmd.easy_install(req)

  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 610, in easy_install

    raise DistutilsError(msg)

distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('python-dateutil>=1.4,<2')

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/protobuf
Storing debug log for failure in /home/fabio/.pip/pip.log

**Comment by fnatalucci** [comment]
I manually download 
https://pypi.python.org/pypi/python-dateutil/1.4.1

./setup.py install 

and after 

launch 
sudo pip install -r requirements.txt
