### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'server_hostname'

### ISSUE THREAD

**Issue by dickies05** [hackappcom/iloot#63]
Got this error. whats wrong?

Output directory : output
Traceback (most recent call last):
  File "C:\phy\iloot-master\iloot.py", line 649, in <module>
    download_backup(args.apple_id, args.password, args.output, args.item_types, args.snapshot, args.combined, args.itunes_style, args.domain, args.threads)
  File "C:\phy\iloot-master\iloot.py", line 569, in download_backup
    authenticateResponse = plist_request("setup.icloud.com", "POST", "/setup/authenticate/$APPLE_ID$", "", {"Authorization": auth})
  File "C:\phy\iloot-master\iloot.py", line 73, in plist_request
    request = conn.request(method, url, body, headers)
  File "C:\Python27\lib\httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "C:\Python27\lib\httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "C:\Python27\lib\httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "C:\Python27\lib\httplib.py", line 893, in _send_output
    self.send(msg)
  File "C:\Python27\lib\httplib.py", line 855, in send
    self.connect()
  File "C:\Python27\lib\httplib.py", line 1274, in connect
    server_hostname=server_hostname)
  File "C:\Python27\lib\ssl.py", line 352, in wrap_socket
    _context=self)
TypeError: __init__() got an unexpected keyword argument 'server_hostname'

**Comment by FiZiX** [comment]
You're probably using a version of Python that's too new for gevent. Try version 2.7.9

**Comment by dickies05** [comment]
Yes you are right. That was the problem
