### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by alw14698** [hackappcom/iloot#71]
I downloaded the iloot-master folder and python 2.7.7 and I cant figure this out past that. I tried double clicking on iloot.py and it opens the cmd window and instantly closes it. There are not any clear instructions on how to use this from a-z, help?!?

**Comment by Jstev3** [comment]
See the README file...

**Comment by moritzdietz** [comment]
Also @alw14698 if you don't know how to run python scripts from command line you really should take a step back and think about learning that first.

**Comment by Judicious** [comment]
In Windows?
Just as the other guys have suggested you should probably look up how to use Python in command line before even thinking about using a project of this nature. However I will try to explain some things for people trying to get started. 
1. You will want to use Python 2.7:
https://www.python.org/downloads/release/python-2711/
2. You may also need Microsoft C++ compiler for Python(otherwise you'll get errors when installing requirements): 
https://www.microsoft.com/en-us/download/details.aspx?id=44266
3. Depending on your version of Python you might also need to install pip manually. However it comes packed with 2.7.11.
4. Python will install to the directory you direct it to, usually C:/Python27 on Windows machines. Once you have installed it you will be running your commands from cmd or "command prompt." You will need to cd to the directory of Python where pip is located(usually /scripts) and then install the requirements outlined in the read me(instead of just requirements.txt it will be the exact file path location of the document)
cd c:\Python27\Scripts
pip install as outlined in the read me file but with exact location of requirements.txt
cd ..
python ILOOT.PY(full path) arguments

**Comment by painkillerxxx** [comment]
Hey I need help, I follow all the steps of Judicious, but the Python fixed This:

Traceback (most recent call last):
  File "C:\Python27\Scripts\iloot.py", line 4, in <module>
    import gevent
  File "C:\Python27\lib\site-packages\gevent__init__.py", line 49, in <module>
    from gevent.hub import get_hub, iwait, wait, PYPY
  File "C:\Python27\lib\site-packages\gevent\hub.py", line 11, in <module>
    from greenlet import greenlet, getcurrent, GreenletExit
ImportError: No module named greenlet


What I doing Bad? or What I Need?

**Comment by Judicious** [comment]
You need to install the requirements.

**Comment by brijesh12345** [comment]
while running this command : python iloot.py ddss@gmail.com dsfsfsdfsdf. got only response.
Working with sdfsdfsdf@gmail.com :dsfsfsdfsdf
Output directory : output 
Available Devices:  0
There are no backups to download!

**Comment by Egospastic** [comment]
I'm getting the message:

Downloading 0 files due to filter

**Comment by Egospastic** [comment]
Never mind, I understand why now. This doesn't seem to have up to date info on these backups. Accounts are saying there are no backups when there definitely are.
