### ISSUE TITLE
KeyError: 'com.apple.Dataclass.Backup'

### ISSUE THREAD

**Issue by mdPlusPlus** [hackappcom/iloot#76]
`python iloot.py %APPLEID% %PASSWORD%`

```
Working with %APPLEID% : %PASSWORD%
Output directory : output
Traceback (most recent call last):
  File "iloot.py", line 679, in <module>
    download_backup(args.apple_id, args.password, args.output, args.item_types, args.snapshot, args.combined, args.itunes_style, args.domain, args.threads, args.keep_existing)
  File "iloot.py", line 607, in download_backup
    client = MobileBackupClient(account_settings, dsPrsID, auth, output_folder)
  File "iloot.py", line 161, in __init__
    mobilebackup_url = account_settings["com.apple.mobileme"]["com.apple.Dataclass.Backup"]["url"]
KeyError: 'com.apple.Dataclass.Backup'
```

What exactly does this mean?

**Comment by alias34** [comment]
same issue happen to me

**Comment by tfranovic** [comment]
I've seen this happen when the account doesn't have any backups present or the account expired (Apple is asking you to update your security questions when you try to login to iCloud).
